# module_name and class_name. Currently, both are same names except the first-letter-case
REVISION_UPDATER_MODULE = 'revisionV0'
REVISION_CLASS_NAME = 'RevisionV0'

## FEED --- FULL (and SMALL for debugging) -- expected to be already available
FILENAME_JSONL_SOURCE_FEED_IN = './data/input/ps_product_en_full_11012023.jsonl'
#FILENAME_JSONL_SOURCE_FEED_IN = './data/input/ps_product_en_full_11012023_10.jsonl'

FILENAME_UPDATED_JSONL_FEED_OUT = './data/output/ps_product_en_full_02122025.jsonl'
FILENAME_UPDATED_TSV_FEED_OUT = './data/output/ps_product_en_full_02122025.tsv'
FILENAME_UPDATED_FEED_ATTRIBUTELIST_OUT = './data/output/ps_product_en_full_02122025.txt'
FILENAME_INJECTED_AVMAP_OUT = './data/output/injected_avmap_02122025.tsv'

# Injected av-map path (initially generated when different catalogs merged. later edited manually)
FILENAME_INJECTED_AV_MAP_IN = './data/input/NONE'
INJECTED_AVMAP_EXCLUDED_ATTRIBUTES = [
    'Action',
    'Actuator',
    'Adhesion Strength',
    'Adhesive Backed',
    'Adhesive Material',
    'Adhesive Type',
    'Adjustment Type',
    'Amperage Rating',
    'Angle',
    'Ansi Code',
    'Applicable Materials',
    'Arbor Size',
    'Armature Voltage',
    'Average Life Hours',
    'Background Color',
    'Backing Material',
    'Ballast Factor',
    'Ballast Type',
    'Barrel Style',
    'Barrel Type',
    'Base',
    'Battery',
    'Battery Capacity',
    'Battery Type',
    'Beam Angle Degree',
    'Bend Degree',
    'Bend Radius',
    'Blade Material',
    'Blade Size',
    'Blade Thickness',
    'Blade Type',
    'Blade Width',
    'Body Material',
    'Body Style',
    'Body Width',
    'Bolt Diameter',
    'Bolt Size',
    'Boot Color',
    'Boot Type',
    'Breaker Type',
    'Bushing Type',
    'Cable Entry',
    'Cable Length',
    'Cable Material',
    'Cable Size',
    'Cable Type',
    'Capacity',
    'Character Height',
    'Character Width',
    'Chuck Size',
    'Chuck Type',
    'Circuit Type',
    'Class',
    'Class Code / Tech Seg',
    'Closed Contact Resistance',
    'Closure Type',
    'Coil Rating',
    'Coil Voltage',
    'Color Code',
    'Color Rendering Index / CRI',
    'Color Temperature',
    'Color Temperature / CCT',
    'Color/Finish',
    'Communication',
    'Conductor / Wire Material',
    'Conductor / Wire Size',
    'Conductor / Wire Stranding',
    'Conductor Material',
    'Conductor Range',
    'Conductor Range AWG Main',
    'Conductor Type',
    'Connection',
    'Connection Size',
    'Connection Type',
    'Connector Type',
    'Contact Configuration',
    'Contact Form',
    'Contact Material',
    'Contact Rating',
    'Contact Resistance',
    'Contact Type',
    'Container Size',
    'Container Type',
    'Control',
    'Control Type',
    'Control Voltage',
    'Cord Length',
    'Cord Type',
    'Core',
    'Cover Type',
    'Crimping Force',
    'Current Rating',
    'Cutting Capacity',
    'Cutting Depth',
    'Cutting Edge Material',
    'Cutting Material',
    'Cutting Size',
    'Data Transfer Rate',
    'Datasheet_MSDS_Sheet',
    'Depth',
    'Designation',
    'Diameter',
    'Die Code',
    'Dimensions',
    'Dimmable',
    'Disconnect Type',
    'Display',
    'Door',
    'Drill Size',
    'Drive Size',
    'Drive Type',
    'Duty',
    'Emitter Light Source',
    'Enclosure',
    'Enclosure Type',
    'Environmental Conditions',
    'Feedback',
    'Fiber Compatibility',
    'Fiber Size',
    'Fiber Type',
    'Finish',
    'Fixture Material',
    'Fixture Type',
    'Flammability',
    'Flammability Rating',
    'Fluids Absorbed',
    'Flute Length',
    'Flute Type',
    'For Use With',
    'Form',
    'Frame',
    'Frame Size',
    'Frequency',
    'Frequency Range',
    'Frequency Rating',
    'Functions',
    'Fuse Rating',
    'Fuse Size',
    'Gang',
    'Gauge',
    'Grade',
    'Grounding',
    'Handle Material',
    'Handle Type',
    'Head Color',
    'Head Diameter',
    'Head Height',
    'Head Type',
    'Head Width',
    'Hex Size',
    'Hole Depth',
    'Hole Diameter',
    'Hole Size',
    'Hook Material',
    'Horsepower Rating',
    'Housing Color',
    'Housing Material',
    'Hp Rating',
    'Hub Size',
    'Illumination',
    'Includes',
    'Indicator',
    'Indicator Type',
    'Inner Diameter Expanded',
    'Inner Diameter Recovered',
    'Input',
    'Input Type',
    'Input Voltage',
    'Inputs',
    'Insertion Loss',
    'Inside Diameter',
    'Insulated Throat',
    'Insulating Material',
    'Insulation',
    'Insulation Class',
    'Insulation Material',
    'Interface',
    'Interface Type',
    'Interrupt Rating',
    'Item Name',
    'Jacket Color',
    'Jacket Material',
    'Jaw Capacity',
    'Jaw Length',
    'Jaw Material',
    'Jaw Size',
    'Jaw Thickness',
    'Jaw Type',
    'Jaw Width',
    'Key Type',
    'Knockouts',
    'Kva Rating',
    'Labels per Package',
    'Lamp Base',
    'Lamp Included',
    'Lamp Shape',
    'Lamp Type',
    'Lamp Wattage',
    'Language',
    'Legend Color',
    'Legend Size',
    'Lens Color',
    'Lens Material',
    'Lens Type',
    'Light Source',
    'Load Capacity',
    'Load Current',
    'Load Rating',
    'Locking Holes',
    'Locking Type',
    'Lockout Material',
    'Lockout Type',
    'Lumens',
    'Marker Height',
    'Material Thickness',
    'Maximum Load',
    'Maximum Load Capacity',
    'Measuring Range',
    'Media',
    'Memory',
    'Minimum Bundle Diameter',
    'Minimum Embedment Depth',
    'Minimum Shrink Temperature',
    'Mounting',
    'Mounting Method',
    'Mounting Type',
    'NEMA Rating',
    'Nema Color',
    'Network',
    'No Load Speed',
    'Nominal Diameter',
    'Nominal Size',
    'Nominal Voltage',
    'Number Of Channels',
    'Number Of Contacts',
    'Number Of Feeders',
    'Number Of Flutes',
    'Number Of Gangs',
    'Number Of Pieces',
    'Number Of Pins',
    'Number Of Pockets',
    'Number Of Points',
    'Number Of Ports',
    'Number Of Positions',
    'Number Of Wires',
    'Number of Fibers',
    'Number of Holes',
    'Number of Lamps',
    'Number of Markers',
    'Number of Outlets',
    'Number of Poles',
    'Number of Receptacles',
    'Number of Spaces',
    'Number of Terminals',
    'Nut Type',
    'Operating Cycles',
    'Operating Frequency',
    'Operating System',
    'Operating Temperature',
    'Operator Type',
    'Orientation',
    'Outlet',
    'Output',
    'Output Circuit Type',
    'Output Current',
    'Output Voltage',
    'Outside Diameter',
    'Overall Height',
    'Overall Length',
    'Overall Width',
    'Packaging Quantity',
    'Packaging Type',
    'Perforated',
    'Perforated Length',
    'Perforated Width',
    'Phase',
    'Pipe Size',
    'Plug Type',
    'Point Type',
    'Port',
    'Power Consumption',
    'Power Factor',
    'Power Rating',
    'Power Supply',
    'Primary Voltage',
    'Print Method',
    'Print Resolution',
    'Print Speed',
    'Print-On Area',
    'Printer Compatibility',
    'Printer Type',
    'Processor',
    'Prop65 Warning',
    'Qty per Card / Sheet',
    'Qty per Roll',
    'Radius',
    'Rank2 14I',
    'Rank2 HI1',
    'Rank2 HI5',
    'Reflector Type',
    'Reset Type',
    'Resistance',
    'Rod Size',
    'Roll Length',
    'Roll Width',
    'Roller Diameter',
    'Roller Material',
    'Run Conductor Size',
    'Saw Diameter',
    'Screen Size',
    'Screw Size',
    'Seal Material',
    'Sensing Beam',
    'Sensing Distance',
    'Sensing Mode',
    'Sensing Range',
    'Sensitivity',
    'Sensor',
    'Sensor Type',
    'Shackle Diameter',
    'Shackle Material',
    'Shackle Width',
    'Shaft Diameter',
    'Shaft Type',
    'Shank Diameter',
    'Shank Length',
    'Shank Material',
    'Shank Size',
    'Shank Type',
    'Shape',
    'Short Circuit Rating',
    'Shrink Ratio',
    'Slot Size',
    'Slot Type',
    'Socket Size',
    'Socket Type',
    'Speed',
    'Speed Rating',
    'Spool Length',
    'Start Type',
    'Strands',
    'Stud Size',
    'Tap Conductor Size',
    'Tap Size',
    'Teeth Per Inch',
    'Teeth Type',
    'Temperature Range',
    'Temperature Rating',
    'Tensile Strength',
    'Terminal Size',
    'Terminal Type',
    'Terminals',
    'Termination',
    'Termination Style',
    'Text Color',
    'Thermal Protection',
    'Thickness',
    'Thread Length',
    'Thread Size',
    'Thread Type',
    'Timing Range',
    'Tip Type',
    'Tongue Size',
    'Tool Length',
    'Tooth Material',
    'Torque Rating',
    'Tpi Or Pitch',
    'Trade Size',
    'Trip Range',
    'Trip Type',
    'User Interface',
    'VOC / Volatile Organic Compounds',
    'Va Rating',
    'Wall Thickness',
    'Wall Thickness Recovered',
    'Warranty',
    'Wattage',
    'Width',
    'Wire Gauge',
    'Wire Size',
    'Wire Type',
    'Wiring Configuration',
    'Working Load Limit',
    'application',
    'brand',
    'catalog_number',
    'catalog_number_partialvalue',
    'category_paths',
    'color',
    'customerpartnumber',
    'description',
    'height',
    'keyword',
    'length',
    'manufacturer',
    'master_upc',
    'material',
    'model',
    'pid_partialvalue',
    'product_brand',
    'size',
    'standards',
    'thumb_image',
    'type',
    'url',
    'velo_brand_lower',
    'velo_manufacturer_lower',
    'velo_material_lower',
    'velo_model_lower',
    'velo_standards_lower',
    'voltage_rating',
    'weight'
]

# URL preambles
PRODUCT_URL_PREFIX = 'https://pacific.bloomreach.com/supply/products/'



