package com.bloomreach.brxdemos.pacificsupply.translate.pixel;

// map generated by parsing API logs. Has two columns: uid and view_id
import java.util.Iterator;
import java.util.HashMap;
import java.io.File;
import java.io.IOException;
import java.io.FileReader;
import java.io.BufferedReader;

public class UidToViewIdMap {

    // uid to view_id map
    private HashMap <String, String> uidViewIdMap;

    public UidToViewIdMap () {
        uidViewIdMap = new HashMap <String, String> ();
    }

    public void load (String UidViewIdMapFilePath) throws Exception {
        File srcFile = null;
        FileReader srcReader = null;
        BufferedReader srcBufferedReader = null;
        String srcLine;
        boolean headerLine;

        try {       
            srcFile = new File (UidViewIdMapFilePath);
            srcReader = new FileReader (srcFile);
            srcBufferedReader = new BufferedReader (srcReader);

            headerLine = true;
            while ((srcLine = srcBufferedReader.readLine ()) != null) {
                String[] tokens;

                // skip header line
                if (headerLine == true) {
                    headerLine = false;
                    continue;
                }

                tokens = srcLine.split ("\t");
                // expected tokens: uid, view_id
                if ((tokens != null) && (tokens.length == 2)) {
                    // column 0: uid
                    // column 1: viewId
                    if ((tokens[0] != null) && (tokens[1] != null))
                        uidViewIdMap.put (tokens[0], tokens[1]);
                }
            }
        } catch (Exception e) {
            System.err.println ("Exception reading UidViewMap: " + e.getMessage ());
        }

        if (srcReader != null)
        {
            try {
                srcReader.close ();
            }
            catch (Exception e)
            {
                System.err.println ("Src reader close exception: " + e.getMessage ());
            }
        }
    }

    public String lookupViewId (String uid) {

        for (Iterator iter = uidViewIdMap.keySet ().iterator(); iter.hasNext(); ) {
            String key = (String) iter.next ();
            if (key.equals (uid) == true) {
                return (uidViewIdMap.get (key));
            }
        }

        return (null);

    }
}
