import logging

class TSVFeed ():

    def __init__ (self):
        return

    def setBRSMFeed (self, brsmFeed):
        self._brsmFeedHandler = brsmFeed

    # generate TSV-style object comprising info for all brsm products
    # returns list of TSV-style-product-objects.
    # This does NOT generate attribute list since it is already generated by dcFeed
    def generateTSVFeed (self):
        # collect list of ALL attributes from ALL products AND their variants
        # That will generate the 'header' line in tsv feed
        _tsvMasterDict = self._collectAllAttributes ()

        # close masterDict for each product and its variants
        _tsvRecords = self._generateProductRecords (_tsvMasterDict)

        return _tsvRecords

    def _collectAllAttributes (self):
        _masterDict = {}

        _brsmProductIterator = self._brsmFeedHandler.getProductIterator ();
        for _aBrsmProduct in _brsmProductIterator: 
            for aKey in _aBrsmProduct.keys ():
                if (aKey in _masterDict) == False:
                    _masterDict [aKey] = ''

        logging.debug ('master keys: ' + str (_masterDict.keys()))
        return _masterDict

    # Note that total dict-entries = product-rec (pacificSupply products don't have variants) 
    def _generateProductRecords (self, masterDict):
        # list of _masterDict objects, containins all products 
        _allTSVRecords = []

        _brsmProductIterator = self._brsmFeedHandler.getProductIterator ();
        for _aBrsmProduct in _brsmProductIterator: 

            _oneProductRecord = masterDict.copy ()
            for aKey in _aBrsmProduct.keys ():
                # since tsv uses tab separator, replace embedded tab with blank (CHEAT !!!)
                # Also since pacificSupply has views, 'price'/'sale-price' values
                # have '|' (view-specific-values). Therefore keep the originalstring as-is
                # (ie, not convert to float in tsv feed)
                value = _aBrsmProduct [aKey]
                if (value != None): 
                    if (type (value) == 'str') and (value.find ('\t') > 0):
                        value = value.replace ('\t', ' ')
                else:
                    value = ''
                _oneProductRecord [aKey] = value
            _allTSVRecords.append (_oneProductRecord); 

        logging.debug ("finish")
        return _allTSVRecords

 
if __name__ == '__main__':
    _tsvFeed = TSVFeed ()
    _tsvFeed.setBRSMFeed (None)
    _tsvFeed.generateTSVFeed ()
 
