# list of { origAttribName, keep/remove, newName, product-level/variant-level }
# names are case sensitive
# if 'remove', remaining fields are unused/undefined
# Note about 'solrInStock'. In order to keep it consistent with 'availability', this attribute
# is removed via this map. However it is added in the code while processing 'availability' flag
ATTRIBUTE_MAP = [
    { 'name': 'OnlineOnly',             'keep': True,  'newName': 'OnlineOnly',       'isProductAttrib': True },
    { 'name': 'launch_date',            'keep': True,  'newName': 'start_date',       'isProductAttrib': True },
    { 'name': 'rating',                 'keep': True,  'newName': 'rating',           'isProductAttrib': True },
    { 'name': 'num_reviews',            'keep': True,  'newName': 'reviews',          'isProductAttrib': True },
    { 'name': 'promotion',              'keep': True,  'newName': 'promotionNow',     'isProductAttrib': True },
    { 'name': 'is_new',                 'keep': True,  'newName': 'condition',        'isProductAttrib': True },
    { 'name': 'collection_id',          'keep': True,  'newName': 'collection',       'isProductAttrib': True },
    { 'name': 'solrInStock',            'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'spuf',                   'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'ageRestriction',         'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'cuisine',                'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'dietaryConsideration',   'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'google_category',        'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'leaf_categories',        'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'producttag',             'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'sts_stores_available',   'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'typeOfFabric',           'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'typeOfFiber',            'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'typeOfMetal',            'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'typeOfWood',             'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'finish',                 'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'searchable',             'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'shape',                  'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'productStatus',          'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'ageRestriction',         'keep': False, 'newName': '',                 'isProductAttrib': True },
    { 'name': 'colorFamily',            'keep': True,  'newName': 'colorFamily',      'isProductAttrib': False },
    { 'name': 'sizeFamily',             'keep': True,  'newName': 'sizeFamily',       'isProductAttrib': False },
    { 'name': 'skuid',                  'keep': True,  'newName': 'skuid',            'isProductAttrib': False },
    { 'name': 'int_skuid',              'keep': True,  'newName': 'int_skuid',        'isProductAttrib': False },
    { 'name': 'sku_large_image',        'keep': False, 'newName': '',                 'isProductAttrib': False },
    { 'name': 'sku_thumb_image',        'keep': True,  'newName': 'swatch_image',     'isProductAttrib': False }
]

BOOLEAN_ATTRIBUTES = [
    'OnlineOnly',
    'inStoreOnly',
    'onSale',
    'pickUpInStore',
    'shipToStore',
    'lowstock'
]

FLOAT_ATTRIBUTES = [
    'price',
    'sale_price',
    'reviews',
    'rating',
    'sale_price_range_min',
    'sale_price_range_max',
    'velo_sku_price',
    'velo_sku_sale_price',
    'margin'
]

# replacement colors are the ones that were already used in this catalog
COLOR_MULTI_REPLACEMENTS = [
    'red',
    'green',
    'blue',
    'Natural',
    'Cream',
    'White',
    'Brown',
    'Acorn',
    'Black',
    'Gold',
    'Ivory',
    'Metallic',
    'Navy',
    'Orange',
    'Pink',
    'Purple',
    'Rust',
    'Silver',
    'Yellow'
]

# following attributes' values contain proper names which need to be obfuscated
ATTRIBUTES_WITH_PROPERNAMES = [
    'title',
    'description'
]

# title, description has text such as 'by <proper_name> ...'. Obfuscate these
# to avoid conflict. Replace these by 'Arti Ficiales'
EXCLUDE_PROPERNAMES = [
    'Omar Escalante',
    'Bunnies by the Bay',
    'Michelle Abrams',
    'Jan Weiss',
    'Douglas Atwill',
    'Elinor Luna',
    'Mariusz Moreau',
    'Frey', # actually Andre-umlaut-e Frey
    'Victoria Borges',
    'Madara',
    'Bella Gomez',
    'Paul Fuentes',
    'Nikol Wikman',
    'Tom Frazier',
    'Maja Gennarsdottir',
    'Henry Wentz',
    'Martin Wickstrom',
    'Wyanne',
    'Jean Seo',
    'Bob Ross',
    'Katrien Soeffers',
    'Danhui Nai',
    'Clara Wells',
    'Mary Urban',
    'Moira Hershey',
    'Paul Duncan',
    'Ruth Fromstein',
    'Synthia SAINT JAMES',
    'Dan Houston',
    'Roseanne Kenny',
    'Kat Nouri',
    'Hario',
    'Haribo',
    'Fiona Watt',
    'Camilla Garofano',
    'Joseph Joseph',
    'Alena Tkach',
    'Samin Nosrat',
    'Jennifer Orkin Lewis',
    'Petra Braun',
    'Kristine Hegre',
    'Chelsea Fagan',
    'Jeff Mezzetta',
    'Lucien Edwards',
    'Arielle Vey',
    'Steven Thomas',
    'Nina Cosford',
    'Barry Timms',
    'Sean Julian',
    'Michelle Schaub',
    'Alice Potter',
    'Rebecca Colby',
    'Penelope Dullaghan',
    'Michael Whaite',
    'Jill McDonald',
    'Matt De La',   # actually Matt De La Pe-tilde-n-a
    'Christian Robinson',
    'Suzanne Chiew',
    'Mechal Renee Roe',
    'Adele Dafflon',
    'Frier',        # actually 'Raphaële Frier'
    'Fronty',       # actually 'Aurelia Fronty',
    'Jeanette Winter',
    'Jennifer Orkin Lewis',
    'Lucy Menzies',
    'Tilly',
    'Uta Krogmann',
    'Kelsey Oseid',
    'Dan Yaccarino',
    'Lizzy Rockwell',
    'Melissa Sweet',
    'Brandon Reese',
    'Moira Butterfield',
    'Jonny Marx',
    'Yi-Hsuan Wu',
    'Alan Macdonald',
    'Magda Brol',
    'S. Marendaz',
    'Carly Gledhill',
    'Alexandra Penfold',
    'Suzanne Kaufman',
    'Meri Meri',
    'Chuao',
    'Jelina',
    'Stella Andromeda',
    'Caitlin Keegan',
    'Cat Cabral',
    'Kim Knoll',
    'Frank C. Clifford',
    'Aurora Kane',
    'Yulia Van Doren',
    'Joel Fagliano',
    'Sutter Buttes', 
    'Davin De Kergommeaux',
    'Kikkerland',
    'Greg Abbot',
    'Anna Dewdney',
    'Ellie Hattie',
    'Tim Warnes',
    'Toby Triumph',
    'David Dean',
    'Clive Gifford',
    'Tim Bradford',
    'Nathan Bryon',
    'Dapo Adeola',
    'Katherine Halligan',
    'Sarah Walsh',
    'Derek Desierto',
    'Katrin Soeffers',
    'Carrie Schmitt',
    'Fatti Burke',
    'Mike Jackson',
    'Anna Membrino',
    'Chelsea Clinton',
    'Alexandra Boiger',
    'Sue Fliess',
    'Natalie Smillie',
    'Dennis Shealy',
    'Mallory C. Loehr',
    'Joey Chou',
    'Nikki Chu',
    'Vashti Harrison',
    'Laura Freeman',
    'Margot Lee Shetterly',
    'Molly Hatch',
    'Fran Bailey',
    'Michelle Obama',
    'Trudeau',
    'Tyson', 
]

# above proper names are randomly replaced by one of
# the following names
CONVERTED_PROPERNAMES = [
    'Arti Ficiales',
    'Ban Diasy',     # swahili
    'Faaf Foliga',   # Samoan
    'Jinko Tekina',  # Japanese
    'Ingong Ui',     # Korean
    'Um Jetna',      # Croatian
    'Kun Stigger',   # Danish
]
