import logging

class TSVFeed ():

    def __init__ (self):
        return

    def setBRSMFeed (self, brsmFeed):
        self._brsmFeedHandler = brsmFeed

    # generate TSV-style object comprising info for all brsm products
    # returns list of TSV-style-product-objects.
    # This does NOT generate attribute list since it is already generated by dcFeed
    def generateTSVFeed (self):
        # collect list of ALL attributes from ALL products AND their variants
        # That will generate the 'header' line in tsv feed
        _tsvMasterDict = self._collectAllAttributes ()

        # close masterDict for each product and its variants
        _tsvRecords = self._generateProductAndVariantRecords (_tsvMasterDict)

        return _tsvRecords

    def _collectAllAttributes (self):
        _masterDict = {}

        _brsmProductIterator = self._brsmFeedHandler.getProductIterator ();
        for _aBrsmProductAndVariants in _brsmProductIterator: 
            _transProductRecord = _aBrsmProductAndVariants ['product']
            _transProductVariants = _aBrsmProductAndVariants ['variants']
            for aKey in _transProductRecord.keys ():
                if (aKey in _masterDict) == False:
                    _masterDict [aKey] = ''

            for aVariant in _transProductVariants:
                for aKey in aVariant.keys ():
                    if (aKey in _masterDict) == False:
                        _masterDict [aKey] = ''

        logging.debug ('master keys: ' + str (_masterDict.keys()))
        return _masterDict

    # Note that total dict-entries = (product-rec + #variant-records) for each product
    def _generateProductAndVariantRecords (self, masterDict):
        # list of _masterDict objects, containins all products and their variants
        _allTSVRecords = []

        _brsmProductIterator = self._brsmFeedHandler.getProductIterator ();
        for _aBrsmProductAndVariants in _brsmProductIterator: 
            _transProductRecord = _aBrsmProductAndVariants ['product']
            _transProductVariants = _aBrsmProductAndVariants ['variants']

            _oneProductRecord = masterDict.copy ()
            for aKey in _transProductRecord.keys ():
                # since tsv uses tab separator, replace embedded tab with blank (CHEAT !!!)
                value = _transProductRecord [aKey]
                if (value != None): 
                    if (type (value) == 'str') and (value.find ('\t') > 0):
                        value = value.replace ('\t', ' ')
                    if (aKey == 'price') or (aKey == 'sale_price'):
                        value = float (value)
                else:
                    value = ''
                _oneProductRecord [aKey] = value
            _allTSVRecords.append (_oneProductRecord); 

            # now dup the product's own record as 'basis' 
            # Each variant's own attributes then overwrite the product's own attribute value 
            for _aTransProductVariant in _transProductVariants:
                _oneVariantRecord = _oneProductRecord.copy ()
                for aKey in _aTransProductVariant.keys ():
                    value = _aTransProductVariant [aKey]
                    if (value != None):
                        if (type (value) == 'str') and (value.find (',') > 0):
                            value = value.replace (',', ' ')
                        if (aKey == 'price') or (aKey == 'sale_price'):
                            value = float (value)
                    else:
                        value = ''
                    _oneVariantRecord [aKey] = value
                _allTSVRecords.append (_oneVariantRecord);

        logging.debug ("finish")
        return _allTSVRecords

 
if __name__ == '__main__':
    _tsvFeed = TSVFeed ()
    _tsvFeed.setBRSMFeed (None)
    _tsvFeed.generateTSVFeed ()
 
